---
title: "Media"
---


As a first-generation student I find dissemination of research of immense importance, and I am lucky that my work is discussed nationally and internationally in the media, and is used in university and science funding policy.

- **RTL EditieNL.** (2025). [Je kent gemiddeld 568 mensen.](https://www.rtl.nl/nieuws/uitzendingen/video/8c795d92-6149-4d55-a86e-16c76c3ddfaf/aflevering-200){target="_blank"} – I was interviewed on national television about our Social Networks paper.
- **Nederlands Dagblad.** (2025). [Een Nederlander kent 568 mensen: ‘Soort zoekt soort en opleiding is een bepalende factor’.](https://www.nd.nl/nieuws/nederland/1275994/een-nederlander-kent-568-mensen-soort-zoekt-soort-en-opleidin){target="_blank"} – piece on our Social Networks paper.
- **De Volkskrant.** (2025). [Een Nederlander kent zo’n 568 mensen: ‘Soort zoekt soort en opleiding is een bepalende factor’.](https://www.volkskrant.nl/wetenschap/een-nederlander-kent-zo-n-568-mensen-soort-zoekt-soort-en-opleiding-is-een-bepalende-factor~b0c4390d){target="_blank"} – piece on our Social Networks paper.
- **Täuber, S. & Mahmoudi, M.** (2024). [Unchanged power dynamics still block progress for under-represented groups in academia.](https://www.nature.com/articles/d41586-024-02130-0){target="_blank"} – Letter in Nature on our QSS paper.
- **AAAS.** (2024). [AAAS President Keith Yamamoto Called on STEMM Community to Move Toward Science Without Walls.](https://www.aaas.org/news/aaas-president-keith-yamamoto-called-stemm-community-move-toward-science-without-walls){target="_blank"} – AAAS president discusses PNAS paper.
- **El Pais.** (2024). [Images on the internet are even more sexist than texts.](https://english.elpais.com/technology/2024-02-15/images-on-the-internet-are-even-more-sexist-than-texts.html){target="_blank"} – Spanish national newspaper interview.
- **Voxweb.** (2023). [Waarom is het voor bepaalde groepen zo moeilijk om hoogleraar te worden?](https://www.voxweb.nl/opinie/waarom-is-het-voor-bepaalde-groepen-zo-moeilijk-om-hoogleraar-te-worden){target="_blank"} – Popular piece by myself.
- **El Mundo.** (2023). [What science can learn from the Beatles](https://www.elmundo.es/papel/futuro/2023/01/16/63c58e6efdddfff9a28b45c8.html){target="_blank"} – Spanish national newspaper interview.
- **Grid News.** (2023). [Groundbreaking patents and scientific discoveries are happening less and less often. Here’s why.](https://www.grid.news/story/science/2023/01/17/groundbreaking-patents-and-scientific-discoveries-are-happening-less-and-less-often-heres-why/){target="_blank"} – Expert quotes.
- **Harvard Business Review.** (2022). [Is Your DEI Progress Undermined by Attention Inequality.](https://hbr.org/2022/10/is-your-dei-progress-undermined-by-attention-inequality/){target="_blank"} – Our PNAS paper quoted.
- **Harvard Business Review.** (2022). [Who Gets to Work in the Digital Economy.](https://hbr.org/2022/08/who-gets-to-work-in-the-digital-economy/){target="_blank"} – Our PNAS paper quoted.
- **Radboud Recharge.** (2022). [Positieve rolmodellen helpen minderheden slagen in de wetenschap.](https://www.radboudrecharge.nl/nl/artikel/positieve-rolmodellen-helpen-minderheden-slagen-in-de-wetenschap){target="_blank"} – Popular piece about our *Socius* study.
- **Nature.** (2021). [Women less likely to win major research awards.](https://www.nature.com/articles/d41586-021-02497-4){target="_blank"} – Interviewed by Nature. 
- **Ghai, S.** (2021). [The Diversity-Innovation Paradox.](https://www.nature.com/articles/s44159-021-00009-9){target="_blank"} – Perspective piece in *Nature Reviews Psychology* about our PNAS study.
- **Stanford News.** (2021). [Stanford research reveals a hidden obstacle for women in academia.](https://news.stanford.edu/2021/12/16/hidden-obstacle-women-academia/){target="_blank"} – Our Research Policy paper discussed.
- **The Guardian.** (2021). [‘Discomfort can break ground’: physicist Stephon Alexander on the value of difference.](https://www.theguardian.com/us-news/2021/sep/01/stephon-alexander-physics-science-brown-university){target="_blank"} – PNAS paper quoted.
- **Sociologie Magazine.** (2021). Ongehoorde Innovatie. – Popular piece I wrote for Sociologie Magazine.
- **Libelle.** (2021). [Hoeveel mensen ken jij? Zóveel is gemiddeld](https://www.libelle.nl/actueel/hoeveel-mensen-ken-jij-zoveel-is-gemiddeld~b7850ef2/){target="_blank"} – Story about our research in Quest.
- **RTL Nieuws.** (2021). [Iedereen kent gemiddeld 540 mensen: 'Oude studievrienden niet meegerekend'](https://www.rtlnieuws.nl/editienl/artikel/5236324/we-kennen-gemiddeld-540-mensen-bij-voornaam-en-maken-praatje){target="_blank"} – Story about our research in Quest.
- **Quest.** (2021). [Hoeveel mensen kent de gemiddelde Nederlander?](https://www.quest.nl/maatschappij/cultuur/a36724478/hoeveel-mensen-kennissen-gemiddelde-nederlander/){target="_blank"} – Data collection and analysis for Quest, cover story "123 slimste vragen".
- **The Michigan Daily.** (2021). [Study shows Black researchers about 55% less likely to receive NIH funding than white researchers.](https://www.michigandaily.com/section/research/study-shows-black-researchers-55-less-likely-receive-nih-funding-white-researchers){target="_blank"} – Our PNAS study cited.
- **The Guardian.**(2020). [The virus-free scientific breakthroughs of 2020, chosen by scientists.](https://www.theguardian.com/science/2020/dec/20/the-virus-free-scientific-breakthroughs-of-2020-chosen-by-scientists){target="_blank"} – Our PNAS study cited.
- **Stanford Social Innovation Review.** (2020). [Science’s Diversity Problem.](https://ssir.org/articles/entry/sciences_diversity_problem){target="_blank"} – Interview about our PNAS study.
- **ZME Science.** (2020). [The diversity paradox in science: minority groups produce more scientific novelty, but their work is often overlooked.](https://www.zmescience.com/science/the-diversity-paradox-in-science-minority-groups-produce-more-scientific-novelty-but-their-work-is-often-overlooked/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+zmescience+%28ZME+Science%29){target="_blank"} – Our PNAS study discussed.
- **AsapSCIENCE.** (2020). [We Need to Talk About Diversity in Science.](https://www.youtube.com/watch?v=zuAnbApl7A0){target="_blank"} – Our PNAS study discussed.
- **USA Today.** (2020). [#BlackBirdersWeek, #BlackInNeuro: Black scientists, physicians are using hashtags to uplift.](https://eu.usatoday.com/story/life/2020/08/04/blackinneuro-blackinchem-can-hashtags-help-black-scientists-build-community-spotlight-excellence/5541431002/){target="_blank"} – Our PNAS study cited.
- **Nature Index.** (2020). [Women and Minority Researchers Have More Original Ideas, But White Men Are Rewarded Faster.](https://www.natureindex.com/news-blog/women-and-minority-researchers-have-more-original-ideas-but-white-men-are-rewarded-faster){target="_blank"} – Our PNAS study discussed.
- **The Hill.** (2020). [Inclusion is our roadmap back to global science dominance.](https://thehill.com/opinion/healthcare/509103-inclusion-is-our-roadmap-back-to-global-science-dominance){target="_blank"} – Our PNAS study discussed.
- **Forbes.** (2020). [New #BlackInNeuro Campaign Connects Bright Minds From Around The World.](https://www.forbes.com/sites/nicolefisher/2020/07/31/new-blackinneuro-campaign-connects-bright-minds-from-around-the-world/#4dbcb47943d4){target="_blank"} – Our PNAS study cited.
- **Times Higher Education.** (2020). [The Scientific Community Needs Constant Self-Assessment on Race and Gender.](https://www.timeshighereducation.com/blog/scientific-community-needs-constant-self-assessment-race-and-gender){target="_blank"} – Opinion piece we wrote on our PNAS study.
- **Scientific American.** (2020). [For Scientific Institutions, Racial Reconciliation Requires Reparations.](https://www.scientificamerican.com/article/for-scientific-institutions-racial-reconciliation-requires-reparations/){target="_blank"} – Quotes our PNAS study.
- **Smithsonian Magazine.** (2020). [Deep Biases Prevent Diverse Talent from Advancing.](https://www.smithsonianmag.com/science-nature/deep-biases-prevent-diverse-talent-advancing-180975033/){target="_blank"} – PNAS interview re-published in Smithsonian Magazine.
- **AGU's EOS.** (2020). [Deep Biases Prevent Diverse Talent from Advancing.](https://eos.org/articles/deep-biases-prevent-diverse-talent-from-advancing){target="_blank"} – News and interview about our PNAS study.
- **Science.** (2020). [Does Diversity Breed Innovation?](https://science.sciencemag.org/content/368/6491/617.6/tab-pdf){target="_blank"} – Our PNAS study is an editor's choice in "In other journals".
- **Nature Research Behavioural & Social Sciences.** (2020). [Behind "The Diversity-Innovation Paradox in Science".](https://socialsciences.nature.com/users/390257-bas-hofstra/posts/behind-the-diversity-innovation-paradox-in-science){target="_blank"} – Behind the paper feature of our PNAS study.
- **Venture Beat.** (2020). [Nvidia apologizes and removes ‘Did it work’ meme tweet.](https://venturebeat.com/2020/04/29/nvidia-apologizes-and-removes-did-it-work-meme-tweet/){target="_blank"} – Quotes our PNAS study.
- **Chemistry World.** (2020). [While Female and Minority Science PhDs’ Ideas Are More Novel They’re Often Overlooked.](https://www.chemistryworld.com/news/while-female-and-minority-science-phds-ideas-are-more-novel-theyre-often-overlooked/4011610.article){target="_blank"} – News and interview about our PNAS study.
- **StukRoodVlees.** (2020). [De Diversiteit-Innovatie Paradox in de Wetenschap.](http://stukroodvlees.nl/de-diversiteit-innovatie-paradox-in-de-wetenschap/){target="_blank"} – Blog about our PNAS study.
- **Stanford GSE.** (2020). [Stanford Study Provides Evidence of the ‘Diversity-Innovation Paradox’ in Academia.](https://ed.stanford.edu/news/stanford-study-provides-evidence-diversity-innovation-paradox-academia){target="_blank"} – Interviewed about our PNAS study.
- **Gizmodo.** (2020). [The Trouble With Stephen Wolfram’s New 'Fundamental Theory of Physics'.](https://gizmodo.com/the-trouble-with-stephen-wolfram-s-new-fundamental-theo-1842985419){target="_blank"} – Quotes our PNAS study.
- **Inside Higher Ed.** (2020). [Risk Without Reward.](https://www.insidehighered.com/news/2020/04/16/underrepresented-scholars-outperform-majority-peers-terms-novel-research){target="_blank"} – News about our PNAS study.
- **NPO Radio 1.** (2018). [Zijn er Ook Glazen Plafonds in de Wetenschap?](https://www.nporadio1.nl/radio-focus/onderwerpen/477620-zijn-er-ook-glazen-plafonds-in-de-wetenschap){target="_blank"} – Interview about my research at Stanford University.
- **Socialevraagstukken.nl.** (2018). [Vrienden en Privacy Vormen op Facebook een Ongelukkige Combinatie.](https://www.socialevraagstukken.nl/vrienden-en-privacy-vormen-op-facebook-een-ongelukkige-combinatie/){target="_blank"} – Blog and research cited.
- **Contexts Magazine.** (2017). [Segregation in Social Networks on Facebook*.](https://contexts.org/blog/segregation-in-facebook-networks/){target="_blank"} – About our 2017 ASR study.
- **Informatie Professional.** (2017). [Promotie over online sociale netwerken en hun gebruikers.](https://informatieprofessional.nl/2017/12/promotie-online-sociale-netwerken-en-gebruikers/){target="_blank"} – About my Ph.D. thesis.
- **Flevopost.** (2017). [Bas Hofstra promoveert.](https://www.flevopost.nl/nieuws/noordoostpolder/520968/bas-hofstra-promoveert.html){target="_blank"} – About my Ph.D. thesis defense.
- **Hofstra, B.** (2017). [Oorzaken van Homogeniteit in Sociale Netwerken.](https://docs.wixstatic.com/ugd/c78d1a_877e7c509b5546c4b3c267d710bb59da.pdf){target="_blank"} – *Mens en Maatschappij*. [our 2017 ASR study “In the spotlight”]
- **Sociologie Magazine.** (2017). [Facebook: Goudmijn Voor Sociologen?](http://docs.wixstatic.com/ugd/c78d1a_a64438f7e29e4aa693b5dc806e1790e0.pdf){target="_blank"} – Interview and research cited.
- **DeCorrespondent.** (2016). [Facebook de schuld geven van Trump. Dát is pas elitair.](http://decorrespondent.nl/5679/facebook-de-schuld-geven-van-trump-dat-is-pas-elitair/276550263-68a5d04e){target="_blank"} – Research mentioned.
- **StukRoodVlees.nl.** (2016). [De kwade invloed van Facebook op de Amerikaanse verkiezingen: broodnodige nuance.](https://stukroodvlees.nl/de-kwade-invloed-van-facebook-op-de-amerikaanse-verkiezingen-broodnodige-nuance/){target="_blank"} – Blog and research cited.
- **Yesonderzoek.nl.** (2016). [Is jouw Facebook-profiel openbaar?](https://www.yesonderzoek.nl/resultaten/is-facebook-profiel-openbaar/){target="_blank"} – Interview and research cited.
- **Bitescience.com.** (2016). [Imitation game: Teens copy each others' privacy settings on Facebook.](https://www.bitescience.com/Knowledgedatabase/Article/tabid/81/ArticleID/329/ArticleName/ImitationGameTeensCopyEachOthersPrivacySettingsonFacebook/Default.aspx){target="_blank"} – Research cited and discussed.
- **Hofstra, B.** (2014). *Online Social Networks: Social Inequality and Social Cohesion*. – [Blog]
