---
title: "News"
---



::: {.columns}


::: {.column width="1/3"}
<div class="news-card">

#### **National Expertisecentrum Wetenschap en Samenleving - Over ons werk**

National Expertisecentrum Wetenschap en Samenleving besteedde onlangs aandacht aan ons werk over wetenschappers in de media. <br> <br>

[Read more →](news/natexp2025.qmd)
</div>
:::


::: {.column width="1/3"}
<div class="news-card">

#### **Interview on national radio about Social Networks study**

I was interview on NPO Radio 5 about how to keep Christmas diners nice when families discuss politics. <br> <br>

[Read more →](news/nporadio52025.qmd)
</div>
:::

::: {.column width="1/3"}
<div class="news-card">

#### **A new paper published in Social Networks**

We just published an open access study in Social Networks! Click here if you're interested in political discussions. <br> <br>

[Read more →](news/socialnetworks2025_2.qmd)
</div>
:::


::: {.column width="1/3"}
<div class="news-card">

#### **New paper in European Sociological Review**

We just published open access in Scientometrics! Check out the cliff's note version here. <br> <br>

[Read more →](news/esr2025.qmd)
</div>
:::


::: {.column width="1/3"}
<div class="news-card">

#### **New paper in Scientometrics**

We just published open access in Scientometrics. What do we study an find? <br> <br>

[Read more →](news/scientometrics2025.qmd)
</div>
:::



::: {.column width="1/3"}
<div class="news-card">

#### **Interview in Trouw**

I was interviewed on how students can build durable networks in the national newspaper Trouw (in Dutch). <br> <br>

[Read more →](news/trouw2025.qmd)
</div>
:::


::: {.column width="1/3"}
<div class="news-card">

#### **New website launch!**

I made a new website: far more versatile for my purposes, more interesting content. <br> <br>

[Read more →](news/launchwebsite2025.qmd)
</div>
:::


::: {.column width="1/3"}
<div class="news-card">

#### **New Paper in Social Networks**

We just published paper in Social Networks: by Beate Volker, Bas Hofstra, Rense Corten, and Frank van Tubergen. <br> <br>
[Read more →](news/socialnetworks2025.qmd)
</div>
:::

::: {.column width="1/3"}
<div class="news-card">

#### **Interview on national television (RTL EditieNL)**

Our Social Networks (2025) study was featured on national television: I was interviewed by RTL EditieNL (in Dutch). <br> <br>

[Read more →](news/editienl2025.qmd)
</div>
:::

::: {.column width="1/3"}
<div class="news-card">

#### **Study featured in national newspaper (de Volkskrant)**

Our Social Networks (2025) study was featured in a national newspaper: de Volskrant wrote a piece about it (in Dutch). <br> <br>

[Read more →](news/volkskrant2025.qmd)
</div>
:::


:::
